// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: media-info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PhotoLibraryBackend.Common.Messages {

  /// <summary>Holder for reflection information generated from media-info.proto</summary>
  public static partial class MediaInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for media-info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MediaInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBtZWRpYS1pbmZvLnByb3RvItQGCglNZWRpYUluZm8SCgoCaWQYASABKAkS",
            "FQoNdGh1bWJuYWlsX3VybBgCIAEoCRIRCgltZWRpYV91cmwYAyABKAkSEQoJ",
            "ZnVsbF9wYXRoGAQgASgJEhEKCWZpbGVfbmFtZRgFIAEoCRIWCg5maWxlX2V4",
            "dGVuc2lvbhgGIAEoCRIeCgptZWRpYV90eXBlGAcgASgOMgouTWVkaWFUeXBl",
            "EhQKDGZpbGVfc2l6ZV9rYhgIIAEoAxIaChJkYXRlX3RpbWVfb3JpZ2luYWwY",
            "CSABKAUSDQoFd2lkdGgYCiABKAUSDgoGaGVpZ2h0GAsgASgFEhcKD3RodW1i",
            "bmFpbF93aWR0aBgMIAEoBRIYChB0aHVtYm5haWxfaGVpZ2h0GA0gASgFEh8K",
            "EnZpZGVvX2R1cmF0aW9uX3NlYxgOIAEoBUgAiAEBEhoKDXBpY3R1cmVfbWFr",
            "ZXIYDyABKAlIAYgBARIQCgN0YWcYECABKAlIAogBARIVCghsYXRpdHVkZRgR",
            "IAEoAUgDiAEBEhoKDWxhdGl0dWRlX3BvbGUYEiABKAlIBIgBARIWCglsb25n",
            "aXR1ZGUYEyABKAFIBYgBARIbCg5sb25naXR1ZGVfc2lkZRgUIAEoCUgGiAEB",
            "EhQKB2NvdW50cnkYFSABKAlIB4gBARITCgZyZWdpb24YFiABKAlICIgBARIV",
            "Cghsb2NhbGl0eRgXIAEoCUgJiAEBEhQKB2FkZHJlc3MYGCABKAlICogBARIS",
            "CgV2ZW51ZRgZIAEoCUgLiAEBEhEKCXRodW1ibmFpbBgaIAEoDBIYCgtpc19m",
            "YXZvcml0ZRgbIAEoCEgMiAEBEhYKCWFsYnVtTmFtZRgcIAEoCUgNiAEBQhUK",
            "E192aWRlb19kdXJhdGlvbl9zZWNCEAoOX3BpY3R1cmVfbWFrZXJCBgoEX3Rh",
            "Z0ILCglfbGF0aXR1ZGVCEAoOX2xhdGl0dWRlX3BvbGVCDAoKX2xvbmdpdHVk",
            "ZUIRCg9fbG9uZ2l0dWRlX3NpZGVCCgoIX2NvdW50cnlCCQoHX3JlZ2lvbkIL",
            "CglfbG9jYWxpdHlCCgoIX2FkZHJlc3NCCAoGX3ZlbnVlQg4KDF9pc19mYXZv",
            "cml0ZUIMCgpfYWxidW1OYW1lKiEKCU1lZGlhVHlwZRIJCgVJTUFHRRAAEgkK",
            "BVZJREVPEAFCJqoCI1Bob3RvTGlicmFyeUJhY2tlbmQuQ29tbW9uLk1lc3Nh",
            "Z2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PhotoLibraryBackend.Common.Messages.MediaType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PhotoLibraryBackend.Common.Messages.MediaInfo), global::PhotoLibraryBackend.Common.Messages.MediaInfo.Parser, new[]{ "Id", "ThumbnailUrl", "MediaUrl", "FullPath", "FileName", "FileExtension", "MediaType", "FileSizeKb", "DateTimeOriginal", "Width", "Height", "ThumbnailWidth", "ThumbnailHeight", "VideoDurationSec", "PictureMaker", "Tag", "Latitude", "LatitudePole", "Longitude", "LongitudeSide", "Country", "Region", "Locality", "Address", "Venue", "Thumbnail", "IsFavorite", "AlbumName" }, new[]{ "VideoDurationSec", "PictureMaker", "Tag", "Latitude", "LatitudePole", "Longitude", "LongitudeSide", "Country", "Region", "Locality", "Address", "Venue", "IsFavorite", "AlbumName" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MediaType {
    [pbr::OriginalName("IMAGE")] Image = 0,
    [pbr::OriginalName("VIDEO")] Video = 1,
  }

  #endregion

  #region Messages
  public sealed partial class MediaInfo : pb::IMessage<MediaInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MediaInfo> _parser = new pb::MessageParser<MediaInfo>(() => new MediaInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MediaInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PhotoLibraryBackend.Common.Messages.MediaInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MediaInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MediaInfo(MediaInfo other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      thumbnailUrl_ = other.thumbnailUrl_;
      mediaUrl_ = other.mediaUrl_;
      fullPath_ = other.fullPath_;
      fileName_ = other.fileName_;
      fileExtension_ = other.fileExtension_;
      mediaType_ = other.mediaType_;
      fileSizeKb_ = other.fileSizeKb_;
      dateTimeOriginal_ = other.dateTimeOriginal_;
      width_ = other.width_;
      height_ = other.height_;
      thumbnailWidth_ = other.thumbnailWidth_;
      thumbnailHeight_ = other.thumbnailHeight_;
      videoDurationSec_ = other.videoDurationSec_;
      pictureMaker_ = other.pictureMaker_;
      tag_ = other.tag_;
      latitude_ = other.latitude_;
      latitudePole_ = other.latitudePole_;
      longitude_ = other.longitude_;
      longitudeSide_ = other.longitudeSide_;
      country_ = other.country_;
      region_ = other.region_;
      locality_ = other.locality_;
      address_ = other.address_;
      venue_ = other.venue_;
      thumbnail_ = other.thumbnail_;
      isFavorite_ = other.isFavorite_;
      albumName_ = other.albumName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MediaInfo Clone() {
      return new MediaInfo(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "thumbnail_url" field.</summary>
    public const int ThumbnailUrlFieldNumber = 2;
    private string thumbnailUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ThumbnailUrl {
      get { return thumbnailUrl_; }
      set {
        thumbnailUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "media_url" field.</summary>
    public const int MediaUrlFieldNumber = 3;
    private string mediaUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MediaUrl {
      get { return mediaUrl_; }
      set {
        mediaUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "full_path" field.</summary>
    public const int FullPathFieldNumber = 4;
    private string fullPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FullPath {
      get { return fullPath_; }
      set {
        fullPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "file_name" field.</summary>
    public const int FileNameFieldNumber = 5;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "file_extension" field.</summary>
    public const int FileExtensionFieldNumber = 6;
    private string fileExtension_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileExtension {
      get { return fileExtension_; }
      set {
        fileExtension_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "media_type" field.</summary>
    public const int MediaTypeFieldNumber = 7;
    private global::PhotoLibraryBackend.Common.Messages.MediaType mediaType_ = global::PhotoLibraryBackend.Common.Messages.MediaType.Image;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PhotoLibraryBackend.Common.Messages.MediaType MediaType {
      get { return mediaType_; }
      set {
        mediaType_ = value;
      }
    }

    /// <summary>Field number for the "file_size_kb" field.</summary>
    public const int FileSizeKbFieldNumber = 8;
    private long fileSizeKb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FileSizeKb {
      get { return fileSizeKb_; }
      set {
        fileSizeKb_ = value;
      }
    }

    /// <summary>Field number for the "date_time_original" field.</summary>
    public const int DateTimeOriginalFieldNumber = 9;
    private int dateTimeOriginal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DateTimeOriginal {
      get { return dateTimeOriginal_; }
      set {
        dateTimeOriginal_ = value;
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 10;
    private int width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 11;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "thumbnail_width" field.</summary>
    public const int ThumbnailWidthFieldNumber = 12;
    private int thumbnailWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ThumbnailWidth {
      get { return thumbnailWidth_; }
      set {
        thumbnailWidth_ = value;
      }
    }

    /// <summary>Field number for the "thumbnail_height" field.</summary>
    public const int ThumbnailHeightFieldNumber = 13;
    private int thumbnailHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ThumbnailHeight {
      get { return thumbnailHeight_; }
      set {
        thumbnailHeight_ = value;
      }
    }

    /// <summary>Field number for the "video_duration_sec" field.</summary>
    public const int VideoDurationSecFieldNumber = 14;
    private int videoDurationSec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VideoDurationSec {
      get { if ((_hasBits0 & 1) != 0) { return videoDurationSec_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        videoDurationSec_ = value;
      }
    }
    /// <summary>Gets whether the "video_duration_sec" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVideoDurationSec {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "video_duration_sec" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVideoDurationSec() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "picture_maker" field.</summary>
    public const int PictureMakerFieldNumber = 15;
    private string pictureMaker_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PictureMaker {
      get { return pictureMaker_ ?? ""; }
      set {
        pictureMaker_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "picture_maker" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPictureMaker {
      get { return pictureMaker_ != null; }
    }
    /// <summary>Clears the value of the "picture_maker" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPictureMaker() {
      pictureMaker_ = null;
    }

    /// <summary>Field number for the "tag" field.</summary>
    public const int TagFieldNumber = 16;
    private string tag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tag {
      get { return tag_ ?? ""; }
      set {
        tag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "tag" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTag {
      get { return tag_ != null; }
    }
    /// <summary>Clears the value of the "tag" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTag() {
      tag_ = null;
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 17;
    private double latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitude {
      get { if ((_hasBits0 & 2) != 0) { return latitude_; } else { return 0D; } }
      set {
        _hasBits0 |= 2;
        latitude_ = value;
      }
    }
    /// <summary>Gets whether the "latitude" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLatitude {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "latitude" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLatitude() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "latitude_pole" field.</summary>
    public const int LatitudePoleFieldNumber = 18;
    private string latitudePole_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LatitudePole {
      get { return latitudePole_ ?? ""; }
      set {
        latitudePole_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "latitude_pole" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLatitudePole {
      get { return latitudePole_ != null; }
    }
    /// <summary>Clears the value of the "latitude_pole" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLatitudePole() {
      latitudePole_ = null;
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 19;
    private double longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitude {
      get { if ((_hasBits0 & 4) != 0) { return longitude_; } else { return 0D; } }
      set {
        _hasBits0 |= 4;
        longitude_ = value;
      }
    }
    /// <summary>Gets whether the "longitude" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLongitude {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "longitude" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLongitude() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "longitude_side" field.</summary>
    public const int LongitudeSideFieldNumber = 20;
    private string longitudeSide_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LongitudeSide {
      get { return longitudeSide_ ?? ""; }
      set {
        longitudeSide_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "longitude_side" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLongitudeSide {
      get { return longitudeSide_ != null; }
    }
    /// <summary>Clears the value of the "longitude_side" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLongitudeSide() {
      longitudeSide_ = null;
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 21;
    private string country_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return country_ ?? ""; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "country" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCountry {
      get { return country_ != null; }
    }
    /// <summary>Clears the value of the "country" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCountry() {
      country_ = null;
    }

    /// <summary>Field number for the "region" field.</summary>
    public const int RegionFieldNumber = 22;
    private string region_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Region {
      get { return region_ ?? ""; }
      set {
        region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "region" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRegion {
      get { return region_ != null; }
    }
    /// <summary>Clears the value of the "region" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRegion() {
      region_ = null;
    }

    /// <summary>Field number for the "locality" field.</summary>
    public const int LocalityFieldNumber = 23;
    private string locality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Locality {
      get { return locality_ ?? ""; }
      set {
        locality_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "locality" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLocality {
      get { return locality_ != null; }
    }
    /// <summary>Clears the value of the "locality" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLocality() {
      locality_ = null;
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 24;
    private string address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Address {
      get { return address_ ?? ""; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "address" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAddress {
      get { return address_ != null; }
    }
    /// <summary>Clears the value of the "address" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAddress() {
      address_ = null;
    }

    /// <summary>Field number for the "venue" field.</summary>
    public const int VenueFieldNumber = 25;
    private string venue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Venue {
      get { return venue_ ?? ""; }
      set {
        venue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "venue" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVenue {
      get { return venue_ != null; }
    }
    /// <summary>Clears the value of the "venue" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVenue() {
      venue_ = null;
    }

    /// <summary>Field number for the "thumbnail" field.</summary>
    public const int ThumbnailFieldNumber = 26;
    private pb::ByteString thumbnail_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Thumbnail {
      get { return thumbnail_; }
      set {
        thumbnail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_favorite" field.</summary>
    public const int IsFavoriteFieldNumber = 27;
    private bool isFavorite_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsFavorite {
      get { if ((_hasBits0 & 8) != 0) { return isFavorite_; } else { return false; } }
      set {
        _hasBits0 |= 8;
        isFavorite_ = value;
      }
    }
    /// <summary>Gets whether the "is_favorite" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsFavorite {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "is_favorite" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsFavorite() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "albumName" field.</summary>
    public const int AlbumNameFieldNumber = 28;
    private string albumName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AlbumName {
      get { return albumName_ ?? ""; }
      set {
        albumName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "albumName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAlbumName {
      get { return albumName_ != null; }
    }
    /// <summary>Clears the value of the "albumName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAlbumName() {
      albumName_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MediaInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MediaInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ThumbnailUrl != other.ThumbnailUrl) return false;
      if (MediaUrl != other.MediaUrl) return false;
      if (FullPath != other.FullPath) return false;
      if (FileName != other.FileName) return false;
      if (FileExtension != other.FileExtension) return false;
      if (MediaType != other.MediaType) return false;
      if (FileSizeKb != other.FileSizeKb) return false;
      if (DateTimeOriginal != other.DateTimeOriginal) return false;
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      if (ThumbnailWidth != other.ThumbnailWidth) return false;
      if (ThumbnailHeight != other.ThumbnailHeight) return false;
      if (VideoDurationSec != other.VideoDurationSec) return false;
      if (PictureMaker != other.PictureMaker) return false;
      if (Tag != other.Tag) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitude, other.Latitude)) return false;
      if (LatitudePole != other.LatitudePole) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitude, other.Longitude)) return false;
      if (LongitudeSide != other.LongitudeSide) return false;
      if (Country != other.Country) return false;
      if (Region != other.Region) return false;
      if (Locality != other.Locality) return false;
      if (Address != other.Address) return false;
      if (Venue != other.Venue) return false;
      if (Thumbnail != other.Thumbnail) return false;
      if (IsFavorite != other.IsFavorite) return false;
      if (AlbumName != other.AlbumName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (ThumbnailUrl.Length != 0) hash ^= ThumbnailUrl.GetHashCode();
      if (MediaUrl.Length != 0) hash ^= MediaUrl.GetHashCode();
      if (FullPath.Length != 0) hash ^= FullPath.GetHashCode();
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (FileExtension.Length != 0) hash ^= FileExtension.GetHashCode();
      if (MediaType != global::PhotoLibraryBackend.Common.Messages.MediaType.Image) hash ^= MediaType.GetHashCode();
      if (FileSizeKb != 0L) hash ^= FileSizeKb.GetHashCode();
      if (DateTimeOriginal != 0) hash ^= DateTimeOriginal.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (ThumbnailWidth != 0) hash ^= ThumbnailWidth.GetHashCode();
      if (ThumbnailHeight != 0) hash ^= ThumbnailHeight.GetHashCode();
      if (HasVideoDurationSec) hash ^= VideoDurationSec.GetHashCode();
      if (HasPictureMaker) hash ^= PictureMaker.GetHashCode();
      if (HasTag) hash ^= Tag.GetHashCode();
      if (HasLatitude) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitude);
      if (HasLatitudePole) hash ^= LatitudePole.GetHashCode();
      if (HasLongitude) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitude);
      if (HasLongitudeSide) hash ^= LongitudeSide.GetHashCode();
      if (HasCountry) hash ^= Country.GetHashCode();
      if (HasRegion) hash ^= Region.GetHashCode();
      if (HasLocality) hash ^= Locality.GetHashCode();
      if (HasAddress) hash ^= Address.GetHashCode();
      if (HasVenue) hash ^= Venue.GetHashCode();
      if (Thumbnail.Length != 0) hash ^= Thumbnail.GetHashCode();
      if (HasIsFavorite) hash ^= IsFavorite.GetHashCode();
      if (HasAlbumName) hash ^= AlbumName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ThumbnailUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ThumbnailUrl);
      }
      if (MediaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MediaUrl);
      }
      if (FullPath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FullPath);
      }
      if (FileName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FileName);
      }
      if (FileExtension.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FileExtension);
      }
      if (MediaType != global::PhotoLibraryBackend.Common.Messages.MediaType.Image) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MediaType);
      }
      if (FileSizeKb != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(FileSizeKb);
      }
      if (DateTimeOriginal != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(DateTimeOriginal);
      }
      if (Width != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Height);
      }
      if (ThumbnailWidth != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(ThumbnailWidth);
      }
      if (ThumbnailHeight != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(ThumbnailHeight);
      }
      if (HasVideoDurationSec) {
        output.WriteRawTag(112);
        output.WriteInt32(VideoDurationSec);
      }
      if (HasPictureMaker) {
        output.WriteRawTag(122);
        output.WriteString(PictureMaker);
      }
      if (HasTag) {
        output.WriteRawTag(130, 1);
        output.WriteString(Tag);
      }
      if (HasLatitude) {
        output.WriteRawTag(137, 1);
        output.WriteDouble(Latitude);
      }
      if (HasLatitudePole) {
        output.WriteRawTag(146, 1);
        output.WriteString(LatitudePole);
      }
      if (HasLongitude) {
        output.WriteRawTag(153, 1);
        output.WriteDouble(Longitude);
      }
      if (HasLongitudeSide) {
        output.WriteRawTag(162, 1);
        output.WriteString(LongitudeSide);
      }
      if (HasCountry) {
        output.WriteRawTag(170, 1);
        output.WriteString(Country);
      }
      if (HasRegion) {
        output.WriteRawTag(178, 1);
        output.WriteString(Region);
      }
      if (HasLocality) {
        output.WriteRawTag(186, 1);
        output.WriteString(Locality);
      }
      if (HasAddress) {
        output.WriteRawTag(194, 1);
        output.WriteString(Address);
      }
      if (HasVenue) {
        output.WriteRawTag(202, 1);
        output.WriteString(Venue);
      }
      if (Thumbnail.Length != 0) {
        output.WriteRawTag(210, 1);
        output.WriteBytes(Thumbnail);
      }
      if (HasIsFavorite) {
        output.WriteRawTag(216, 1);
        output.WriteBool(IsFavorite);
      }
      if (HasAlbumName) {
        output.WriteRawTag(226, 1);
        output.WriteString(AlbumName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ThumbnailUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ThumbnailUrl);
      }
      if (MediaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MediaUrl);
      }
      if (FullPath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FullPath);
      }
      if (FileName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FileName);
      }
      if (FileExtension.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FileExtension);
      }
      if (MediaType != global::PhotoLibraryBackend.Common.Messages.MediaType.Image) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MediaType);
      }
      if (FileSizeKb != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(FileSizeKb);
      }
      if (DateTimeOriginal != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(DateTimeOriginal);
      }
      if (Width != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Height);
      }
      if (ThumbnailWidth != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(ThumbnailWidth);
      }
      if (ThumbnailHeight != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(ThumbnailHeight);
      }
      if (HasVideoDurationSec) {
        output.WriteRawTag(112);
        output.WriteInt32(VideoDurationSec);
      }
      if (HasPictureMaker) {
        output.WriteRawTag(122);
        output.WriteString(PictureMaker);
      }
      if (HasTag) {
        output.WriteRawTag(130, 1);
        output.WriteString(Tag);
      }
      if (HasLatitude) {
        output.WriteRawTag(137, 1);
        output.WriteDouble(Latitude);
      }
      if (HasLatitudePole) {
        output.WriteRawTag(146, 1);
        output.WriteString(LatitudePole);
      }
      if (HasLongitude) {
        output.WriteRawTag(153, 1);
        output.WriteDouble(Longitude);
      }
      if (HasLongitudeSide) {
        output.WriteRawTag(162, 1);
        output.WriteString(LongitudeSide);
      }
      if (HasCountry) {
        output.WriteRawTag(170, 1);
        output.WriteString(Country);
      }
      if (HasRegion) {
        output.WriteRawTag(178, 1);
        output.WriteString(Region);
      }
      if (HasLocality) {
        output.WriteRawTag(186, 1);
        output.WriteString(Locality);
      }
      if (HasAddress) {
        output.WriteRawTag(194, 1);
        output.WriteString(Address);
      }
      if (HasVenue) {
        output.WriteRawTag(202, 1);
        output.WriteString(Venue);
      }
      if (Thumbnail.Length != 0) {
        output.WriteRawTag(210, 1);
        output.WriteBytes(Thumbnail);
      }
      if (HasIsFavorite) {
        output.WriteRawTag(216, 1);
        output.WriteBool(IsFavorite);
      }
      if (HasAlbumName) {
        output.WriteRawTag(226, 1);
        output.WriteString(AlbumName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (ThumbnailUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ThumbnailUrl);
      }
      if (MediaUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MediaUrl);
      }
      if (FullPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullPath);
      }
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (FileExtension.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileExtension);
      }
      if (MediaType != global::PhotoLibraryBackend.Common.Messages.MediaType.Image) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MediaType);
      }
      if (FileSizeKb != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FileSizeKb);
      }
      if (DateTimeOriginal != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DateTimeOriginal);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (ThumbnailWidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ThumbnailWidth);
      }
      if (ThumbnailHeight != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ThumbnailHeight);
      }
      if (HasVideoDurationSec) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VideoDurationSec);
      }
      if (HasPictureMaker) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PictureMaker);
      }
      if (HasTag) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Tag);
      }
      if (HasLatitude) {
        size += 2 + 8;
      }
      if (HasLatitudePole) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(LatitudePole);
      }
      if (HasLongitude) {
        size += 2 + 8;
      }
      if (HasLongitudeSide) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(LongitudeSide);
      }
      if (HasCountry) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (HasRegion) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Region);
      }
      if (HasLocality) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Locality);
      }
      if (HasAddress) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Address);
      }
      if (HasVenue) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Venue);
      }
      if (Thumbnail.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(Thumbnail);
      }
      if (HasIsFavorite) {
        size += 2 + 1;
      }
      if (HasAlbumName) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AlbumName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MediaInfo other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.ThumbnailUrl.Length != 0) {
        ThumbnailUrl = other.ThumbnailUrl;
      }
      if (other.MediaUrl.Length != 0) {
        MediaUrl = other.MediaUrl;
      }
      if (other.FullPath.Length != 0) {
        FullPath = other.FullPath;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.FileExtension.Length != 0) {
        FileExtension = other.FileExtension;
      }
      if (other.MediaType != global::PhotoLibraryBackend.Common.Messages.MediaType.Image) {
        MediaType = other.MediaType;
      }
      if (other.FileSizeKb != 0L) {
        FileSizeKb = other.FileSizeKb;
      }
      if (other.DateTimeOriginal != 0) {
        DateTimeOriginal = other.DateTimeOriginal;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.ThumbnailWidth != 0) {
        ThumbnailWidth = other.ThumbnailWidth;
      }
      if (other.ThumbnailHeight != 0) {
        ThumbnailHeight = other.ThumbnailHeight;
      }
      if (other.HasVideoDurationSec) {
        VideoDurationSec = other.VideoDurationSec;
      }
      if (other.HasPictureMaker) {
        PictureMaker = other.PictureMaker;
      }
      if (other.HasTag) {
        Tag = other.Tag;
      }
      if (other.HasLatitude) {
        Latitude = other.Latitude;
      }
      if (other.HasLatitudePole) {
        LatitudePole = other.LatitudePole;
      }
      if (other.HasLongitude) {
        Longitude = other.Longitude;
      }
      if (other.HasLongitudeSide) {
        LongitudeSide = other.LongitudeSide;
      }
      if (other.HasCountry) {
        Country = other.Country;
      }
      if (other.HasRegion) {
        Region = other.Region;
      }
      if (other.HasLocality) {
        Locality = other.Locality;
      }
      if (other.HasAddress) {
        Address = other.Address;
      }
      if (other.HasVenue) {
        Venue = other.Venue;
      }
      if (other.Thumbnail.Length != 0) {
        Thumbnail = other.Thumbnail;
      }
      if (other.HasIsFavorite) {
        IsFavorite = other.IsFavorite;
      }
      if (other.HasAlbumName) {
        AlbumName = other.AlbumName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ThumbnailUrl = input.ReadString();
            break;
          }
          case 26: {
            MediaUrl = input.ReadString();
            break;
          }
          case 34: {
            FullPath = input.ReadString();
            break;
          }
          case 42: {
            FileName = input.ReadString();
            break;
          }
          case 50: {
            FileExtension = input.ReadString();
            break;
          }
          case 56: {
            MediaType = (global::PhotoLibraryBackend.Common.Messages.MediaType) input.ReadEnum();
            break;
          }
          case 64: {
            FileSizeKb = input.ReadInt64();
            break;
          }
          case 72: {
            DateTimeOriginal = input.ReadInt32();
            break;
          }
          case 80: {
            Width = input.ReadInt32();
            break;
          }
          case 88: {
            Height = input.ReadInt32();
            break;
          }
          case 96: {
            ThumbnailWidth = input.ReadInt32();
            break;
          }
          case 104: {
            ThumbnailHeight = input.ReadInt32();
            break;
          }
          case 112: {
            VideoDurationSec = input.ReadInt32();
            break;
          }
          case 122: {
            PictureMaker = input.ReadString();
            break;
          }
          case 130: {
            Tag = input.ReadString();
            break;
          }
          case 137: {
            Latitude = input.ReadDouble();
            break;
          }
          case 146: {
            LatitudePole = input.ReadString();
            break;
          }
          case 153: {
            Longitude = input.ReadDouble();
            break;
          }
          case 162: {
            LongitudeSide = input.ReadString();
            break;
          }
          case 170: {
            Country = input.ReadString();
            break;
          }
          case 178: {
            Region = input.ReadString();
            break;
          }
          case 186: {
            Locality = input.ReadString();
            break;
          }
          case 194: {
            Address = input.ReadString();
            break;
          }
          case 202: {
            Venue = input.ReadString();
            break;
          }
          case 210: {
            Thumbnail = input.ReadBytes();
            break;
          }
          case 216: {
            IsFavorite = input.ReadBool();
            break;
          }
          case 226: {
            AlbumName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ThumbnailUrl = input.ReadString();
            break;
          }
          case 26: {
            MediaUrl = input.ReadString();
            break;
          }
          case 34: {
            FullPath = input.ReadString();
            break;
          }
          case 42: {
            FileName = input.ReadString();
            break;
          }
          case 50: {
            FileExtension = input.ReadString();
            break;
          }
          case 56: {
            MediaType = (global::PhotoLibraryBackend.Common.Messages.MediaType) input.ReadEnum();
            break;
          }
          case 64: {
            FileSizeKb = input.ReadInt64();
            break;
          }
          case 72: {
            DateTimeOriginal = input.ReadInt32();
            break;
          }
          case 80: {
            Width = input.ReadInt32();
            break;
          }
          case 88: {
            Height = input.ReadInt32();
            break;
          }
          case 96: {
            ThumbnailWidth = input.ReadInt32();
            break;
          }
          case 104: {
            ThumbnailHeight = input.ReadInt32();
            break;
          }
          case 112: {
            VideoDurationSec = input.ReadInt32();
            break;
          }
          case 122: {
            PictureMaker = input.ReadString();
            break;
          }
          case 130: {
            Tag = input.ReadString();
            break;
          }
          case 137: {
            Latitude = input.ReadDouble();
            break;
          }
          case 146: {
            LatitudePole = input.ReadString();
            break;
          }
          case 153: {
            Longitude = input.ReadDouble();
            break;
          }
          case 162: {
            LongitudeSide = input.ReadString();
            break;
          }
          case 170: {
            Country = input.ReadString();
            break;
          }
          case 178: {
            Region = input.ReadString();
            break;
          }
          case 186: {
            Locality = input.ReadString();
            break;
          }
          case 194: {
            Address = input.ReadString();
            break;
          }
          case 202: {
            Venue = input.ReadString();
            break;
          }
          case 210: {
            Thumbnail = input.ReadBytes();
            break;
          }
          case 216: {
            IsFavorite = input.ReadBool();
            break;
          }
          case 226: {
            AlbumName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
