namespace PhotoLibraryBackend.Common;

public class MediaFileInfo
{
    // GUID autogenerated
    public string Id { get; set; } = string.Empty;

    public string FullPath { get; set; } = string.Empty;

    public string FileName { get; set; } = string.Empty;

    public string FileExt { get; set; } = string.Empty;

    public long FileSize { get; set; }

    public string FileHash { get; set; } = string.Empty;

    public DateTime DateTimeOriginal { get; set; }

    public string? PictureMaker { get; set; }

    public decimal? Latitude { get; set; }
    public string? LatitudePole { get; set; }

    public decimal? Longitude { get; set; }
    public string? LongitudeSide { get; set; }

    public int? Width { get; set; }
    public int? Height { get; set; }

    public int? ThumbnailWidth { get; set; }
    public int? ThumbnailHeight { get; set; }


    public ExifOrientation? Orientation { get; set; }

    public byte[]? Thumbnail { get; set; }

    public int? VideoDurationSec { get; set; }

    public bool Deleted { get; set; }


    public string? TagLabel { get; set; }

    public int? MediaAddressId { get; set; }
    public MediaAddress? MediaAddress { get; set; }

    public Album? Album { get; set; }
}
